services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    container_name: nextcloud-container
    environment:
    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=admin
    - PHP_UPLOAD_LIMIT=99999999M
    - PHP_MEMORY_LIMIT=999999999M
    - APACHE_BODY_LIMIT=0
    ports:
    - "80:80"
    volumes:
    - "./data:/var/www/html"

