services:
  nginx:
    image: nginx:1.27.3
 #   container_name: nginx-server
    restart: unless-stopped
    networks:
      - porto-network
    ports:
     - "80:80"
    depends_on:
     - web
    volumes:
      - "/etc/nginx:/etc/nginx"
      - "/usr/lib/nginx:/usr/lib/nginx"
      - "/usr/share/nginx/html:/usr/share/nginx/html"
 #    - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
   #   - "/etc/nginx/sites-enabled:/etc/nginx/sites-enabled"
    # - "/etc/nginx/sites-available:/etc/nginx/sites-available"
    

networks:
  porto-network:
    driver: bridge
