services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

